# Generated by Django 5.1.1 on 2024-10-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='stock',
            field=models.IntegerField(default=10),
        ),
    ]
