# Generated by Django 5.1.1 on 2024-10-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_prefered_categories_userprofile_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='categories',
            field=models.CharField(max_length=200),
        ),
    ]
