# Generated by Django 5.1.1 on 2024-10-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_postimage_remove_post_descrption_post_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('AD', 'Admin'), ('US', 'User')], default='US', max_length=2),
        ),
    ]
