# Generated by Django 5.1.1 on 2024-10-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='categories',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
